name: Auto-Merge Release PRs

on:
  schedule:
    - cron: '0 */6 * * *' # Run every 6 hours
  workflow_dispatch:
    inputs:
      time_elapsed:
        description: 'Time elapsed since PR creation (e.g. "24h", "1d").'
        required: true
        default: '1d'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  auto-merge-releases:
    name: Auto Merge Releases
    permissions:
      contents: write # Required to merge PRs
      pull-requests: write # Required to merge PRs
    uses: TimSchoenle/actions/.github/workflows/maintenance-timed-auto-pr-approve.yaml@b2a739020943dda20be41530fcf2cda2845f1881 # workflows-maintenance-timed-auto-pr-approve-v1.2.2
    with:
      time_elapsed: ${{ inputs.time_elapsed || '7d' }}
      branch_pattern: 'release-please--branches--%'
      trusted_authors: '253958393,248313786' # actions-maintenance-bot, automatic-release-manager
    secrets:
      app_id: ${{ secrets.RELEASE_BOT_APP_ID }}
      private_key: ${{ secrets.RELEASE_BOT_PRIVATE_KEY }}
