name: Renovate Auto Approve

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  auto-approve-renovate:
    name: Auto Approve Renovate
    uses: TimSchoenle/actions/.github/workflows/maintenance-auto-approve-renovate.yaml@80fdf326726ebba51424160889534a2e85d869bc # workflows-maintenance-auto-approve-renovate-v1.1.1
    permissions:
      pull-requests: write # To approve PRs
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
