name: Renovate Auto Approve

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  auto-approve-renovate:
    name: Auto Approve Renovate
    uses: TimSchoenle/actions/.github/workflows/maintenance-auto-approve-renovate.yaml@a6781085565a0ded808f0b24d1d41b7ba5d331d0 # workflows-maintenance-auto-approve-renovate-v1.1.3
    permissions:
      pull-requests: write # To approve PRs
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
