name: Renovate Auto Approve

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  auto-approve-renovate:
    name: Auto Approve Renovate
    uses: TimSchoenle/actions/.github/workflows/maintenance-auto-approve-renovate.yaml@9f86b67e242750886e9a3ba0eaf7b102824bb886 # workflows-maintenance-auto-approve-renovate-v1.1.2
    permissions:
      pull-requests: write # To approve PRs
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
